# This workflow will verify the exercises in the repository.
#
# Requires scripts:
# - bin/verify-exercises

name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  verify_exercises:
    # TODO: replace with another image if required to run the tests (optional)
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      # TODO: setup any tooling that is required to run the tests (optional)
      # E.g. install a specific version of a programming language
      # E.g. install packages via apt/apk/yum/etc.
      # Find GitHub Actions to setup tooling here:
      # - https://github.com/actions/?q=setup&type=&language=
      # - https://github.com/actions/starter-workflows/tree/main/ci
      # - https://github.com/marketplace?type=actions&query=setup
      # - name: Use <setup tooling>
      #   uses: <action to setup tooling>

      # TODO: install any dependencies (optional)
      # E.g. npm install, bundle install, etc.
      # - name: Install project dependencies
      #   run: <install dependencies>

      - name: Verify all exercises
        run: bin/verify-exercises
